import { Prompt } from './types';

// Helper to generate IDs
const id = (prefix: string, idx: number) => `${prefix}-${idx}`;

export const QUESTIONS_S1: Prompt[] = [
  { id: id('S1', 1), text: "What would you do if you won the lottery today?", stage: 'S1', difficulty: 1, type: 'question' },
  { id: id('S1', 2), text: "What would be your ideal weekend?", stage: 'S1', difficulty: 1, type: 'question' },
  { id: id('S1', 3), text: "What’s a hot take you believe in?", stage: 'S1', difficulty: 2, type: 'question' },
  { id: id('S1', 4), text: "What’s something you’re working on or plan to do in the near future?", stage: 'S1', difficulty: 1, type: 'question' },
  { id: id('S1', 5), text: "Any hyper-fixations in the past?", stage: 'S1', difficulty: 2, type: 'question' },
  { id: id('S1', 6), text: "What’s a skill or hobby you’ve picked up that surprised you in some way?", stage: 'S1', difficulty: 2, type: 'question' },
];

export const QUESTIONS_S2: Prompt[] = [
  { id: id('S2', 1), text: "List three things that you are looking for in a friend/partner", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 2), text: "What’s your favorite piece of media, and why?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 3), text: "Things that a friend does that annoys you.", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 4), text: "Who in your life has influenced you the most, and how?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 5), text: "How do you know when you can really trust someone?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 6), text: "If you could spend a year doing/learning anything without worrying about money or practicality, what would it be?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 7), text: "What setting do you feel most like yourself?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 8), text: "What’s your ideal hangout like?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 9), text: "What’s a trait about you that you would like to change?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 10), text: "When you’re facing a problem, what do you usually do?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 11), text: "What’s a fear you’ve overcome, or one you’re still working on?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 12), text: "Difference between who you are with friends and with family?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 13), text: "Something you’ve always wanted to get into but had trouble with?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 14), text: "What’s something you used to prioritize that you don’t anymore?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 15), text: "What’s something you could talk about for hours without getting bored?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 16), text: "Most serious injury?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 17), text: "What does “success” mean to you?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 18), text: "If you could give your younger self one piece of insight, what would it be?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 19), text: "What’s a hobby you gave up on and why? Would you like to try again?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 20), text: "What’s your ideal job?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 21), text: "If you could relive a day from your past exactly as it happened, which would you choose?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 22), text: "What’s a version of your life you sometimes wonder about—a path you didn’t take?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 23), text: "Choosing between what was expected of you and what you want.", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 24), text: "What’s the most exciting part of visiting a new country for you?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 25), text: "How do you feel about silence in conversations or friendships?", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 26), text: "When do you prefer to be alone rather than with people or vice versa.", stage: 'S2', difficulty: 2, type: 'question' },
  { id: id('S2', 27), text: "What kind of event/environment do you think inspires change?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 28), text: "What makes time go by faster for you?", stage: 'S2', difficulty: 1, type: 'question' },
  { id: id('S2', 29), text: "When did you grow up to be “you”, and why?", stage: 'S2', difficulty: 3, type: 'question' },
  { id: id('S2', 30), text: "Share a life hack that you think more people could follow.", stage: 'S2', difficulty: 1, type: 'question' },
];

export const QUESTIONS_S3: Prompt[] = [
  { id: id('S3', 1), text: "What do you think about marriage/having a child?", stage: 'S3', difficulty: 3, type: 'question' },
  { id: id('S3', 2), text: "What’s one thing you would want to change about your past if you had to pick one?", stage: 'S3', difficulty: 3, type: 'question' },
  { id: id('S3', 3), text: "What do you tend to do in a team?", stage: 'S3', difficulty: 2, type: 'question' },
  { id: id('S3', 4), text: "What pattern do you keep repeating in your life that you wish you could break?", stage: 'S3', difficulty: 3, type: 'question' },
  { id: id('S3', 5), text: "What’s something you know about yourself that you rarely admit out loud?", stage: 'S3', difficulty: 3, type: 'question' },
  { id: id('S3', 6), text: "When have you felt most alone, even when surrounded by people?", stage: 'S3', difficulty: 3, type: 'question' },
  { id: id('S3', 7), text: "One thing you’ve always wanted to do but never found the people to do it with?", stage: 'S3', difficulty: 2, type: 'question' },
  { id: id('S3', 8), text: "When are you most “in the zone”?", stage: 'S3', difficulty: 2, type: 'question' },
  { id: id('S3', 9), text: "What are the constants throughout your life?", stage: 'S3', difficulty: 3, type: 'question' },
];

export const ACTIVITIES: Prompt[] = [
  { id: id('ACT', 1), text: "2 truths 1 lie", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 2), text: "Choosing a photo from your library to tell a story", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 3), text: "First impression of a player at the table (can spin again to decide who)", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 4), text: "Show lock screen/home screen on phone and explain why", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 5), text: "Show the latest picture you have in your gallery", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 6), text: "Show a picture that makes no sense out of context", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 7), text: "Show the last thing you took a picture of that wasn’t a person", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 8), text: "Show a photo that shows where you spend a lot of time", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 9), text: "Show a childhood photo or a photo when you were younger", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 10), text: "Give a compliment to a player (can spin again to decide who)", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 11), text: "Give a compliment to everyone at the table", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 12), text: "Hold a plank during the next answer (individual only)", stage: 'S1', difficulty: 2, type: 'activity' },
  { id: id('ACT', 13), text: "Take a group photo", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 14), text: "Take a photo of each player", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 15), text: "Tell a childhood story in 10 seconds", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 16), text: "Find one thing you and someone else have in common", stage: 'S1', difficulty: 1, type: 'activity' },
  { id: id('ACT', 17), text: "Take a photo of a player (spin again to decide who)", stage: 'S1', difficulty: 1, type: 'activity' },
  // Special trigger for pointing game
  { id: 'TRIGGER_POINTING', text: "On the count of three, everyone point to the person who…", stage: 'S1', difficulty: 1, type: 'activity' },
];

export const POINTING_PACK: Prompt[] = [
  { id: id('PNT', 1), text: "has the cleanest room", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 2), text: "has the messiest room", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 3), text: "takes the longest to get ready", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 4), text: "is secretly the best at flirting", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 5), text: "gives the strongest “green flag” energy", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 6), text: "falls in love the fastest", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 7), text: "gives the best relationship advice", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 8), text: "gives the worst relationship advice", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 9), text: "is secretly the most romantic", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 10), text: "looks intimidating but is actually soft", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 11), text: "has main-character energy", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 12), text: "is the best listener", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 13), text: "you’d text at 2 a.m.", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 14), text: "asks the best questions", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 15), text: "seems like they smell really good", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 16), text: "would give the best first impression on parents", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 17), text: "would get the most people’s numbers in one night", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 18), text: "has the most interesting stories", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 19), text: "has the best fashion sense", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 20), text: "feels like they have a secret talent no one expects", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 21), text: "looks like they’re good at dancing", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 22), text: "has the best smile", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 23), text: "would survive the longest in a zombie apocalypse", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 24), text: "would fall for an obvious scam", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 25), text: "would say “I’m not drunk” when they absolutely are", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 26), text: "you think would be the best kisser", stage: 'S3', difficulty: 2, type: 'pointing' }, // S3 Only
  { id: id('PNT', 27), text: "has the best “date me” aura", stage: 'S1', difficulty: 1, type: 'pointing' },
  { id: id('PNT', 28), text: "has the strongest “silent rizz”", stage: 'S1', difficulty: 1, type: 'pointing' },
];